# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d908eb3d8659f740f633383b9fab3bfb6ac7d3dc9852fc4c563ff7d77ac038f199a27103d7fec4eec24db7feee1892649f1b22cb3ff04bd6c90f0e169ca1d8

test:
  secret_key_base: e79fc668b60d2c8b258c85e19e7fb718c1ac1ce2396d09b59147881e1fa8b553b81358641e4f77b2410fb3c5ce7328d5b0305c7ff8e73fbb7c9584a111c1aa01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
